unbind C-b
set -g prefix C-a
bind C-a send-prefix
set -g mouse on
# Resize panes with Alt + arrow keys
bind -r h resize-pane -L 5
bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5
